variables:
  DOCKER_REGISTRY: 20.1.0.201:25000
  NAMESPACE: aio
  REF_NAME: $CI_COMMIT_REF_NAME

  PROJECT_NAME: aiovms
  BRANCH_NAME: $CI_COMMIT_REF_NAME
  TAG: $CI_COMMIT_REF_NAME
  TAG_SLUG: $CI_COMMIT_REF_SLUG
  IMAGE_NAME: $NAMESPACE/$PROJECT_NAME
  INIT_SERVER_IMAGE_NAME: $NAMESPACE/init_server
  SONAR_HOST_URL: http://20.1.0.201:29000
  BUILD_PATH: /builds/aio/vms

stages:
  - build
  - push
#  - deploy
#  - pack
#  - scan

build_image_testing:
  stage: build
  tags:
    - docker
  script:
#    - 'chmod +x update_version.sh'
#    - './update_version.sh ${TAG_SLUG}'
    - 'echo "build: ${IMAGE_NAME}:${TAG_SLUG}"'
    - 'docker build -t "${IMAGE_NAME}:${TAG_SLUG}" -f ./Dockerfile ./'
#    - 'docker build -t "${INIT_SERVER_IMAGE_NAME}:${TAG_SLUG}" -f ./InitServerDockerFile ./'
  only:
    - branches
  only:
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^develop$/

push_image_testing:
  stage: push
  tags:
    - docker
  script:
    - 'echo "push: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG_SLUG}"'
    - 'docker tag ${IMAGE_NAME}:${TAG_SLUG} ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG_SLUG}'
    - 'docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG_SLUG}'
    - 'docker rmi ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG_SLUG}'
#    - 'docker tag ${INIT_SERVER_IMAGE_NAME}:${TAG_SLUG} ${DOCKER_REGISTRY}/${INIT_SERVER_IMAGE_NAME}:${TAG_SLUG}'
#    - 'docker push ${DOCKER_REGISTRY}/${INIT_SERVER_IMAGE_NAME}:${TAG_SLUG}'
#    - 'docker rmi ${DOCKER_REGISTRY}/${INIT_SERVER_IMAGE_NAME}:${TAG_SLUG}'
  only:
    - branches
  only:
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^develop$/

build_image:
  stage: build
  tags:
    - docker
  script:
    #- 'chmod +x update_version.sh'
    #- './update_version.sh ${TAG}'
    - 'echo "build: ${IMAGE_NAME}:${TAG}"'
    - 'docker build -t "${IMAGE_NAME}:${TAG}" -f ./Dockerfile ./'
    - 'docker tag ${IMAGE_NAME}:${TAG} ${IMAGE_NAME}:latest'
#    - 'docker build -t "${INIT_SERVER_IMAGE_NAME}:${TAG}" -f ./InitServerDockerFile ./'
#    - 'docker tag ${INIT_SERVER_IMAGE_NAME}:${TAG} ${INIT_SERVER_IMAGE_NAME}:latest'
  only:
    - tags


push_image:
  stage: push
  tags:
    - docker
  script:
    - 'echo "push: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}"'
    - 'docker tag ${IMAGE_NAME}:${TAG} ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}'
    - 'docker tag ${IMAGE_NAME}:latest ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest'
    - 'docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}'
    - 'docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest'
    - 'docker rmi ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}'
    - 'docker rmi ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest'


    - 'docker image prune -f'
  only:
    - master
  only:
    - tags

deploy_dev:
  stage: deploy
  tags:
    - ssh-204
  variables:
    GIT_STRATEGY: none
  script:
    - 'echo "deploy on develop server: ${IMAGE_NAME}:${TAG_SLUG}"'
    - 'docker pull ${IMAGE_NAME}:${TAG_SLUG}'
    - 'cd /home/swomc/aio/nms'
    - 'sh start.sh'
#    - 'cd /home/swomc/aio/init-server'
#    - 'docker pull ${INIT_SERVER_IMAGE_NAME}:${TAG}'
#    - 'sh start.sh'
#    - 'docker image prune -f'
  only:
    - branches
  only:
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^develop$/
  allow_failure: true
