// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/qoderwork/aiovms"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cameras": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "按租户分页查询摄像头，支持名称/IP模糊搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "摄像头列表（分页）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名称或 IP 关键字",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码（从 1 开始）",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Camera"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "创建摄像头并注册到 MediaMTX，status 初始为 connecting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "创建摄像头",
                "parameters": [
                    {
                        "description": "摄像头参数（含 password 明文）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/camera.CreateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Camera"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "删除当前租户下所有摄像头并批量注销 MediaMTX 路径",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "清空所有摄像头",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "deleted": {
                                                    "type": "integer",
                                                    "format": "int64"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/batch": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "批量创建摄像头，每行独立处理，部分失败不影响其他行",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "批量导入摄像头",
                "parameters": [
                    {
                        "description": "摄像头列表（1~100 条）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/camera.BatchCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/camera.batchResult"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/discover": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "通过 WS-Discovery 在本网段探测 ONVIF 设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "ONVIF 设备发现",
                "parameters": [
                    {
                        "description": "可选，timeout_sec 缺省 5 秒",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/onvif.DiscoveredDevice"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/probe": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "直接连接指定 IP 的 ONVIF 设备获取信息和 RTSP 流地址（绕过组播，适用于 Docker 环境）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "ONVIF 单播探测",
                "parameters": [
                    {
                        "description": "探测请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/onvif.DiscoveredDevice"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/scan": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "扫描指定 CIDR 网段内所有 ONVIF 设备（单播并发探测，适用于 Docker 环境）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "ONVIF 网段扫描",
                "parameters": [
                    {
                        "description": "扫描请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/onvif.DiscoveredDevice"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/status": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "返回所有摄像头的轻量级状态，供 NMS 订阅",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "摄像头状态列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "按 ID 查询单个摄像头",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "摄像头详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Camera"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "更新摄像头参数，可选重置 password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "更新摄像头",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "摄像头参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/camera.UpdateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "软删除摄像头并从 MediaMTX 注销",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "删除摄像头",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/connect": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "触发与 ONVIF/RTSP 设备的连接",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "连接摄像头",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/disconnect": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "断开与设备的连接",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "断开摄像头",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/snapshot": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "触发设备抓拍并返回快照信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "抓拍快照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/stream": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "返回 MediaMTX 的 HTTP-FLV 地址（一期默认启用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "获取 HTTP-FLV 播放地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "url": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/stream-urls": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "返回 FLV/HLS/WebRTC 三种播放地址（一期前端默认使用 HTTP-FLV）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "获取全部流地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.StreamURLs"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/stream/hls": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "返回 MediaMTX 的 HLS 地址，二期开放",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "获取 HLS 播放地址（二期）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "url": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/stream/webrtc": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "返回 MediaMTX 的 WebRTC 地址，二期开放",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "摄像头管理"
                ],
                "summary": "获取 WebRTC 播放地址（二期）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "url": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/recordings": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "按摄像头 + 时间范围分页查询录像",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像管理"
                ],
                "summary": "录像列表（分页）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "camera_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间下限（RFC3339）",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间上限（RFC3339）",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码（从 1 开始）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Recording"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/recordings/cameras/{id}/start": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "对指定摄像头立即开始手动录像",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像管理"
                ],
                "summary": "手动开始录像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/recordings/cameras/{id}/stop": {
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "对指定摄像头立即停止手动录像",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像管理"
                ],
                "summary": "手动停止录像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/recordings/{id}": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "按 ID 查询录像，返回录像信息和回放 URL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像管理"
                ],
                "summary": "录像详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "录像 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "play_url": {
                                                    "type": "string"
                                                },
                                                "recording": {
                                                    "$ref": "#/definitions/model.Recording"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "删除录像文件和数据库记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像管理"
                ],
                "summary": "删除录像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "录像 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "按租户查询录像计划，可选按摄像头过滤",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像计划"
                ],
                "summary": "录像计划列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像头 ID",
                        "name": "camera_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.RecordSchedule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "为摄像头创建周期性录像计划",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像计划"
                ],
                "summary": "创建录像计划",
                "parameters": [
                    {
                        "description": "录像计划参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schedule.CreateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.RecordSchedule"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/schedules/{id}": {
            "put": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "更新指定录像计划的参数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像计划"
                ],
                "summary": "更新录像计划",
                "parameters": [
                    {
                        "type": "string",
                        "description": "计划 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "录像计划参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schedule.UpdateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "删除指定录像计划",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像计划"
                ],
                "summary": "删除录像计划",
                "parameters": [
                    {
                        "type": "string",
                        "description": "计划 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/schedules/{id}/toggle": {
            "patch": {
                "security": [
                    {
                        "TenantHeader": []
                    },
                    {
                        "UserHeader": []
                    }
                ],
                "description": "翻转录像计划的 enabled 标志",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "录像计划"
                ],
                "summary": "启停录像计划",
                "parameters": [
                    {
                        "type": "string",
                        "description": "计划 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.RecordSchedule"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "camera.BatchCreateRequest": {
            "type": "object",
            "required": [
                "cameras"
            ],
            "properties": {
                "cameras": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/camera.CreateCameraRequest"
                    }
                }
            }
        },
        "camera.CreateCameraRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "description": "RTSP / ONVIF",
                    "type": "string"
                },
                "site_id": {
                    "type": "string"
                },
                "stream_url": {
                    "type": "string"
                },
                "sub_stream_url": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "camera.StreamURLs": {
            "type": "object",
            "properties": {
                "flv": {
                    "type": "string"
                },
                "hls": {
                    "type": "string"
                },
                "webrtc": {
                    "type": "string"
                }
            }
        },
        "camera.UpdateCameraRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "site_id": {
                    "type": "string"
                },
                "stream_url": {
                    "type": "string"
                },
                "sub_stream_url": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "camera.batchResult": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.Camera": {
            "type": "object",
            "properties": {
                "codec": {
                    "description": "H.264 / H.265",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "fps": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "license_id": {
                    "type": "integer"
                },
                "longitude": {
                    "type": "number"
                },
                "manufacturer": {
                    "type": "string"
                },
                "media_mtx_path": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "description": "RTSP / ONVIF",
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                },
                "site_id": {
                    "type": "string"
                },
                "status": {
                    "description": "online / offline / connecting / disconnected / error",
                    "type": "string"
                },
                "stream_url": {
                    "type": "string"
                },
                "sub_stream_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.RecordSchedule": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "end_time": {
                    "description": "\"20:00\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_action": {
                    "description": "start / stop / idle",
                    "type": "string"
                },
                "last_triggered_at": {
                    "type": "string"
                },
                "license_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "description": "\"08:00\"",
                    "type": "string"
                },
                "stream_type": {
                    "description": "main / sub — 一期预留，暂不生效，录像始终用主码流",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "weekdays": {
                    "description": "\"1,2,3,4,5\" (Sun=0)",
                    "type": "string"
                }
            }
        },
        "model.Recording": {
            "type": "object",
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "codec": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "license_id": {
                    "type": "integer"
                },
                "media_mtx_path": {
                    "description": "MediaMTX path name (e.g. \"cam-a1b2c3d4\"), used for playback URL",
                    "type": "string"
                },
                "record_type": {
                    "description": "reserved; currently all \"scheduled\"",
                    "type": "string"
                },
                "resolution": {
                    "type": "string"
                },
                "session_id": {
                    "description": "link to RecordingSession; nullable for legacy files",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "description": "recording / complete / truncated",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "onvif.DiscoveredDevice": {
            "type": "object",
            "properties": {
                "firmware": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                },
                "stream_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "schedule.CreateScheduleRequest": {
            "type": "object",
            "required": [
                "camera_id"
            ],
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "end_time": {
                    "description": "\"20:00\"",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "description": "\"08:00\"",
                    "type": "string"
                },
                "stream_type": {
                    "description": "main / sub — 一期预留，暂不生效，录像始终用主码流",
                    "type": "string"
                },
                "weekdays": {
                    "description": "\"1,2,3,4,5\" (Sun=0)",
                    "type": "string"
                }
            }
        },
        "schedule.UpdateScheduleRequest": {
            "type": "object",
            "required": [
                "camera_id"
            ],
            "properties": {
                "camera_id": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "end_time": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "stream_type": {
                    "description": "main / sub — 一期预留，暂不生效",
                    "type": "string"
                },
                "weekdays": {
                    "type": "string"
                }
            }
        },
        "utils.PaginatedResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/utils.pageData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "utils.pageData": {
            "type": "object",
            "properties": {
                "list": {},
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "TenantHeader": {
            "description": "Tenant (license) ID, forwarded by NMS. Use \"default\" for tenant 1.",
            "type": "apiKey",
            "name": "X-License-Id",
            "in": "header"
        },
        "UserHeader": {
            "description": "User ID, forwarded by NMS.",
            "type": "apiKey",
            "name": "X-User-Id",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AIO VMS API",
	Description:      "Video Management Service for AIO NMS.\nProvides camera management, recording, and scheduling APIs. Internal service invoked by NMS proxy.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
